### ISSUE TITLE
problem in generating .mlir

### ISSUE THREAD

**Issue by jackwatson01234** [hanchenye/scalehls#27]
Hi,

I wanna try to evaluate keccak speed up in your tools. 
in sample codes you have multiple .mlir (in different size) file but there is no command to make it from source file ( .c files).
How can I make this files from for example keccak.c file?

**Comment by zslwyuan** [comment]
Hi @jackwatson01234 ,

Maybe you can follow the steps in the Section 3 in README: https://github.com/hanchenye/scalehls#3-try-scalehls
Then you might understand the entire flow to use the infrastructures in this repo ^_^

**Comment by jackwatson01234** [comment]
in this part, 
you are using scalehls-clang to pars c code but output is not affine style. also scalehls-opt using .mlir with affine format to optimize code.

**Comment by hanchenye** [comment]
I want to note that we are also collaborating with [Polygeist](https://github.com/wsmoses/Polygeist) folks. There's a high possibility we'll add Polygeist into this repository as a submodule in the near future. You may also want try Polygeist out to generate affine MLIR.
