### ISSUE TITLE
scalehls cannot utilize dsp48 primitive

### ISSUE THREAD

**Issue by eeriecl** [hanchenye/scalehls#36]
![image](https://user-images.githubusercontent.com/38751853/146022819-6e23ce88-d48a-4553-8449-9e47475ef1c3.png)

you may see with very very little modification, scalehls cannot utilize dsp48 at all

**Comment by hanchenye** [comment]
@eeriecl Are you using the DSE engine to optimize the equivalent function?

**Comment by hanchenye** [comment]
Auh, it seems this is caused by an the loop-perfectization pass -- `c_tmp = 0.0f` is not correctly perfectized. Thanks for the catch!

**Comment by hanchenye** [comment]
Fixed in eb8743d3a994e22e036b6229032825d65998eccb.
