### ISSUE TITLE
Regression Test Error

### ISSUE THREAD

**Issue by Oxygen-Chu** [hanchenye/scalehls#38]
I see the regression-test error when run "./build-scalehls.sh". It cannot find "mlir-clang" routine.
<img width="469" alt="fig1" src="https://user-images.githubusercontent.com/22520522/151123191-3c914e12-9a52-4f61-9dbe-f9267cff4633.png">

But with execution "sudo find / -name mlir-clang", I see the "mlir-clang" routine exists, but not within ScaleHLS-asked directory.
<img width="472" alt="fig2" src="https://user-images.githubusercontent.com/22520522/151123425-246439c8-ff1c-49f8-9aa8-d879f4b26639.png">

**Comment by hanchenye** [comment]
Fixed in 0995c3cfecfbaaccfbc088c71abb78772b8d2e25, thanks!
