### ISSUE TITLE
Cannot find any explanation for "config.json"

### ISSUE THREAD

**Issue by Oxygen-Chu** [hanchenye/scalehls#39]
I just cannot find somewhere to explain the every arguments within "config.json"
<img width="196" alt="Screenshot 2022-01-28 133546" src="https://user-images.githubusercontent.com/22520522/151493186-87e41c54-8f95-4ec3-a01e-1cdb95cdbefc.png">

**Comment by hanchenye** [comment]
Fixed in d356071a537bb2adc2c2206b15c8a2e1b591d3dc.
